# Generated by Django 3.2.7 on 2021-10-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('cuisine', models.CharField(max_length=300)),
                ('shelf_life', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
